//! Order commands - requests from clients to modify orders

use super::types::{
    CartItemInput, ItemChanges, LossReason, PaymentInput, ServiceType, SplitItem, VoidType,
};
use serde::{Deserialize, Serialize};

/// Order command wrapper
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCommand {
    /// Idempotency key (generated by client)
    pub command_id: String,
    /// Command timestamp
    pub timestamp: i64,
    /// Operator ID
    pub operator_id: String,
    /// Operator name (snapshot for audit)
    pub operator_name: String,
    /// Command payload
    pub payload: OrderCommandPayload,
}

/// Command payload variants
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum OrderCommandPayload {
    // ========== Order Lifecycle ==========
    /// Open a new table/order
    OpenTable {
        #[serde(skip_serializing_if = "Option::is_none")]
        table_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        table_name: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        zone_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        zone_name: Option<String>,
        #[serde(default = "default_guest_count")]
        guest_count: i32,
        #[serde(default)]
        is_retail: bool,
    },

    /// Complete an order (receipt_number from snapshot)
    CompleteOrder {
        order_id: String,
        /// 服务类型（零售订单结单时确认：堂食/外带）
        #[serde(skip_serializing_if = "Option::is_none")]
        service_type: Option<ServiceType>,
    },

    /// Void an order
    VoidOrder {
        order_id: String,
        /// 作废类型（默认 Cancelled）
        #[serde(default)]
        void_type: VoidType,
        /// 损失原因（仅 LossSettled 时使用）
        #[serde(skip_serializing_if = "Option::is_none")]
        loss_reason: Option<LossReason>,
        /// 损失金额（仅 LossSettled 时使用）
        #[serde(skip_serializing_if = "Option::is_none")]
        loss_amount: Option<f64>,
        /// 备注
        #[serde(skip_serializing_if = "Option::is_none")]
        note: Option<String>,
        /// Authorizer for void operation
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    // ========== Item Operations ==========
    /// Add items to order
    AddItems {
        order_id: String,
        items: Vec<CartItemInput>,
    },

    /// Modify an item
    ModifyItem {
        order_id: String,
        instance_id: String,
        /// Number of items to modify (for partial modification)
        #[serde(skip_serializing_if = "Option::is_none")]
        affected_quantity: Option<i32>,
        changes: ItemChanges,
        /// Authorizer for changes requiring permission
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Remove an item
    RemoveItem {
        order_id: String,
        instance_id: String,
        /// Quantity to remove (None = remove all)
        #[serde(skip_serializing_if = "Option::is_none")]
        quantity: Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Authorizer for removal
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Restore a removed item
    RestoreItem {
        order_id: String,
        instance_id: String,
    },

    // ========== Payment Operations ==========
    /// Add payment to order
    AddPayment {
        order_id: String,
        payment: PaymentInput,
    },

    /// Cancel a payment
    CancelPayment {
        order_id: String,
        payment_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Authorizer for cancellation
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Split by items (菜品分单)
    SplitByItems {
        order_id: String,
        payment_method: String,
        items: Vec<SplitItem>,
        /// 现金实收（仅 CASH 有值）
        #[serde(skip_serializing_if = "Option::is_none")]
        tendered: Option<f64>,
    },

    /// Split by amount (金额分单)
    SplitByAmount {
        order_id: String,
        split_amount: f64,
        payment_method: String,
        /// 现金实收（仅 CASH 有值）
        #[serde(skip_serializing_if = "Option::is_none")]
        tendered: Option<f64>,
    },

    /// Start AA split (锁定人数 + 支付第一份)
    StartAaSplit {
        order_id: String,
        total_shares: i32,
        shares: i32,
        payment_method: String,
        /// 现金实收（仅 CASH 有值）
        #[serde(skip_serializing_if = "Option::is_none")]
        tendered: Option<f64>,
    },

    /// Pay AA split (后续 AA 支付)
    PayAaSplit {
        order_id: String,
        shares: i32,
        payment_method: String,
        /// 现金实收（仅 CASH 有值）
        #[serde(skip_serializing_if = "Option::is_none")]
        tendered: Option<f64>,
    },

    // ========== Table Operations ==========
    /// Move order to another table
    MoveOrder {
        order_id: String,
        target_table_id: String,
        target_table_name: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        target_zone_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        target_zone_name: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Merge two orders
    MergeOrders {
        source_order_id: String,
        target_order_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    // ========== Other Operations ==========
    /// Update order info (receipt_number is immutable - set at OpenTable)
    UpdateOrderInfo {
        order_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        guest_count: Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        table_name: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        is_pre_payment: Option<bool>,
    },

    /// Toggle rule skip status
    ToggleRuleSkip {
        order_id: String,
        rule_id: String,
        skipped: bool,
    },

    // ========== Order-level Adjustments ==========
    /// Apply order-level manual discount (percent or fixed, mutually exclusive)
    ApplyOrderDiscount {
        order_id: String,
        /// 百分比折扣 (0-100)，None = 清除
        #[serde(skip_serializing_if = "Option::is_none")]
        discount_percent: Option<f64>,
        /// 固定金额折扣，None = 清除
        #[serde(skip_serializing_if = "Option::is_none")]
        discount_fixed: Option<f64>,
        /// 都为 None = 取消折扣；percent 和 fixed 互斥
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Comp (gift) an item - mark as free with reason and authorizer
    CompItem {
        order_id: String,
        instance_id: String,
        /// Number of items to comp (can be partial)
        quantity: i32,
        /// Reason for comp (required for audit)
        reason: String,
        /// Authorizer ID (required)
        authorizer_id: String,
        /// Authorizer name (required)
        authorizer_name: String,
    },

    /// Uncomp (reverse comp) an item - restore original price
    UncompItem {
        order_id: String,
        /// The comped item's instance_id
        instance_id: String,
        /// Authorizer ID (required)
        authorizer_id: String,
        /// Authorizer name (required)
        authorizer_name: String,
    },

    /// Apply order-level surcharge (fixed amount)
    ApplyOrderSurcharge {
        order_id: String,
        /// 固定附加费金额，None = 清除
        #[serde(skip_serializing_if = "Option::is_none")]
        surcharge_amount: Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    // ========== Order Note ==========
    /// Add or clear order-level note (覆盖式，空字符串 = 清除)
    AddOrderNote {
        order_id: String,
        /// 备注内容，空字符串 = 清除备注
        note: String,
    },
}

fn default_guest_count() -> i32 {
    1
}

impl OrderCommand {
    /// Create a new command with auto-generated ID
    pub fn new(operator_id: String, operator_name: String, payload: OrderCommandPayload) -> Self {
        Self {
            command_id: uuid::Uuid::new_v4().to_string(),
            timestamp: crate::util::now_millis(),
            operator_id,
            operator_name,
            payload,
        }
    }

    /// Get the order ID this command targets (if applicable)
    pub fn target_order_id(&self) -> Option<&str> {
        match &self.payload {
            OrderCommandPayload::OpenTable { .. } => None,
            OrderCommandPayload::CompleteOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::VoidOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::AddItems { order_id, .. } => Some(order_id),
            OrderCommandPayload::ModifyItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::RemoveItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::RestoreItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::AddPayment { order_id, .. } => Some(order_id),
            OrderCommandPayload::CancelPayment { order_id, .. } => Some(order_id),
            OrderCommandPayload::SplitByItems { order_id, .. } => Some(order_id),
            OrderCommandPayload::SplitByAmount { order_id, .. } => Some(order_id),
            OrderCommandPayload::StartAaSplit { order_id, .. } => Some(order_id),
            OrderCommandPayload::PayAaSplit { order_id, .. } => Some(order_id),
            OrderCommandPayload::MoveOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::MergeOrders {
                source_order_id, ..
            } => Some(source_order_id),
            OrderCommandPayload::UpdateOrderInfo { order_id, .. } => Some(order_id),
            OrderCommandPayload::ToggleRuleSkip { order_id, .. } => Some(order_id),
            OrderCommandPayload::CompItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::UncompItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::ApplyOrderDiscount { order_id, .. } => Some(order_id),
            OrderCommandPayload::ApplyOrderSurcharge { order_id, .. } => Some(order_id),
            OrderCommandPayload::AddOrderNote { order_id, .. } => Some(order_id),
        }
    }
}
