//! Order commands - requests from clients to modify orders

use serde::{Deserialize, Serialize};
use super::types::{CartItemInput, ItemChanges, PaymentInput, SplitItem};

/// Order command wrapper
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCommand {
    /// Idempotency key (generated by client)
    pub command_id: String,
    /// Command timestamp
    pub timestamp: i64,
    /// Operator ID
    pub operator_id: String,
    /// Operator name (snapshot for audit)
    pub operator_name: String,
    /// Command payload
    pub payload: OrderCommandPayload,
}

/// Command payload variants
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum OrderCommandPayload {
    // ========== Order Lifecycle ==========

    /// Open a new table/order
    OpenTable {
        #[serde(skip_serializing_if = "Option::is_none")]
        table_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        table_name: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        zone_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        zone_name: Option<String>,
        #[serde(default = "default_guest_count")]
        guest_count: i32,
        #[serde(default)]
        is_retail: bool,
    },

    /// Complete an order
    CompleteOrder {
        order_id: String,
        receipt_number: String,
    },

    /// Void an order
    VoidOrder {
        order_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// Restore a voided order (reserved, not implemented)
    RestoreOrder {
        order_id: String,
    },

    // ========== Item Operations ==========

    /// Add items to order
    AddItems {
        order_id: String,
        items: Vec<CartItemInput>,
    },

    /// Modify an item
    ModifyItem {
        order_id: String,
        instance_id: String,
        /// Number of items to modify (for partial modification)
        #[serde(skip_serializing_if = "Option::is_none")]
        affected_quantity: Option<i32>,
        changes: ItemChanges,
        /// Authorizer for changes requiring permission
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Remove an item
    RemoveItem {
        order_id: String,
        instance_id: String,
        /// Quantity to remove (None = remove all)
        #[serde(skip_serializing_if = "Option::is_none")]
        quantity: Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Authorizer for removal
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Restore a removed item (reserved, not implemented)
    RestoreItem {
        order_id: String,
        instance_id: String,
    },

    // ========== Payment Operations ==========

    /// Add payment to order
    AddPayment {
        order_id: String,
        payment: PaymentInput,
    },

    /// Cancel a payment
    CancelPayment {
        order_id: String,
        payment_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Authorizer for cancellation
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        authorizer_name: Option<String>,
    },

    /// Split bill payment
    SplitOrder {
        order_id: String,
        split_amount: f64,
        payment_method: String,
        items: Vec<SplitItem>,
    },

    // ========== Table Operations ==========

    /// Move order to another table
    MoveOrder {
        order_id: String,
        target_table_id: String,
        target_table_name: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        target_zone_name: Option<String>,
    },

    /// Merge two orders
    MergeOrders {
        source_order_id: String,
        target_order_id: String,
    },

    // ========== Other Operations ==========

    /// Update order info
    UpdateOrderInfo {
        order_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        receipt_number: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        guest_count: Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        table_name: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        is_pre_payment: Option<bool>,
    },
}

fn default_guest_count() -> i32 {
    1
}

impl OrderCommand {
    /// Create a new command with auto-generated ID
    pub fn new(operator_id: String, operator_name: String, payload: OrderCommandPayload) -> Self {
        Self {
            command_id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            operator_id,
            operator_name,
            payload,
        }
    }

    /// Get the order ID this command targets (if applicable)
    pub fn target_order_id(&self) -> Option<&str> {
        match &self.payload {
            OrderCommandPayload::OpenTable { .. } => None,
            OrderCommandPayload::CompleteOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::VoidOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::RestoreOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::AddItems { order_id, .. } => Some(order_id),
            OrderCommandPayload::ModifyItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::RemoveItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::RestoreItem { order_id, .. } => Some(order_id),
            OrderCommandPayload::AddPayment { order_id, .. } => Some(order_id),
            OrderCommandPayload::CancelPayment { order_id, .. } => Some(order_id),
            OrderCommandPayload::SplitOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::MoveOrder { order_id, .. } => Some(order_id),
            OrderCommandPayload::MergeOrders { source_order_id, .. } => Some(source_order_id),
            OrderCommandPayload::UpdateOrderInfo { order_id, .. } => Some(order_id),
        }
    }
}
