//! Localized text for receipt / credit note / kitchen ticket rendering.
//!
//! All text is `&'static str` — zero allocation, used directly in hot render paths.

/// Localized receipt text for all three renderers:
/// - Tauri `receipt_renderer.rs` (customer receipt)
/// - Edge `credit_note_renderer.rs` (refund receipt)
/// - Edge `renderer.rs` (kitchen ticket)
pub struct ReceiptText {
    // ── decimal format ────────────────────────────────────────────
    /// Decimal separator: "," for es-ES, "." for others
    pub decimal_separator: &'static str,

    // ── receipt status titles (centered, double-size) ─────────────
    pub voided: &'static str,
    pub bill: &'static str,
    pub reprint: &'static str,

    // ── receipt header ────────────────────────────────────────────
    pub receipt_title: &'static str,
    pub tax_id_label: &'static str,
    pub phone_label: &'static str,
    pub email_label: &'static str,

    // ── receipt metadata lines ────────────────────────────────────
    pub receipt_num_label: &'static str,
    pub queue_label: &'static str,
    pub table_label: &'static str,
    pub terminal_label: &'static str,
    pub guests_label: &'static str,
    pub opened_label: &'static str,
    pub closed_label: &'static str,
    pub void_reason_label: &'static str,

    // ── item table header ─────────────────────────────────────────
    pub col_qty: &'static str,
    pub col_desc: &'static str,
    pub col_price: &'static str,
    pub col_amount: &'static str,

    // ── item discount sub-lines ───────────────────────────────────
    pub discount_prefix: &'static str,
    pub before_price_label: &'static str,

    // ── subtotal area ─────────────────────────────────────────────
    pub subtotal_label: &'static str,
    pub savings: &'static str,
    pub total_units_label: &'static str,
    pub units_word: &'static str,

    // ── tax breakdown table ───────────────────────────────────────
    pub col_tax_rate: &'static str,
    pub col_tax_base: &'static str,
    pub col_tax_amount: &'static str,

    // ── total + footer ────────────────────────────────────────────
    pub total_label: &'static str,
    pub tax_included: &'static str,
    pub farewell: &'static str,

    // ── credit note (refund receipt) ──────────────────────────────
    pub credit_note_title: &'static str,
    pub credit_note_num_label: &'static str,
    pub original_receipt_label: &'static str,
    pub col_article: &'static str,
    pub col_cant: &'static str,
    pub iva_label: &'static str,
    pub credit_subtotal_label: &'static str,
    pub refund_method_label: &'static str,
    pub refund_reason_label: &'static str,
    pub authorizer_label: &'static str,
    pub cashier_label: &'static str,
    pub refund_cash: &'static str,
    pub refund_card: &'static str,

    // ── kitchen ticket ────────────────────────────────────────────
    pub takeaway_title: &'static str,
    pub takeaway_tag: &'static str,
    pub spec_label: &'static str,
    pub reprint_indicator: &'static str,
}

/// Build localized receipt text for the given locale.
///
/// Supported: `"zh-CN"`, `"en"` / `"en-US"` / `"en-GB"`, default `es-ES`.
pub fn receipt_text(locale: &str) -> ReceiptText {
    match locale {
        "zh-CN" => ReceiptText {
            decimal_separator: ".",
            voided: "*** 已作废 ***",
            bill: "*** 账单 ***",
            reprint: "*** 重印 ***",
            receipt_title: "收据",
            tax_id_label: "税号:",
            phone_label: "电话:",
            email_label: "Email:",
            receipt_num_label: "单号:",
            queue_label: "订单: #",
            table_label: "桌台:",
            terminal_label: "终端:",
            guests_label: "人数:",
            opened_label: "开台:",
            closed_label: "结台:  ",
            void_reason_label: "作废:",
            col_qty: "数量",
            col_desc: "品名",
            col_price: "单价",
            col_amount: "金额",
            discount_prefix: "> 折扣",
            before_price_label: " 原价 ",
            subtotal_label: "小计",
            savings: "节省",
            total_units_label: "合计件数:",
            units_word: "件",
            col_tax_rate: "税率",
            col_tax_base: "税基",
            col_tax_amount: "税额",
            total_label: "合计",
            tax_included: "含税",
            farewell: "*** 谢谢惠顾 ***",
            credit_note_title: "退款凭证",
            credit_note_num_label: "凭证号:",
            original_receipt_label: "原始收据:",
            col_article: "商品",
            col_cant: "数量",
            iva_label: "税额:",
            credit_subtotal_label: "小计:",
            refund_method_label: "退款方式:",
            refund_reason_label: "退款原因:",
            authorizer_label: "授权人:",
            cashier_label: "收银员:",
            refund_cash: "现金",
            refund_card: "刷卡",
            takeaway_title: "外带",
            takeaway_tag: "[外带]",
            spec_label: "规格:",
            reprint_indicator: "重印",
        },
        "en" | "en-US" | "en-GB" => ReceiptText {
            decimal_separator: ".",
            voided: "*** VOIDED ***",
            bill: "*** BILL ***",
            reprint: "*** REPRINT ***",
            receipt_title: "RECEIPT",
            tax_id_label: "Tax ID:",
            phone_label: "Tel:",
            email_label: "Email:",
            receipt_num_label: "No:",
            queue_label: "ORDER: #",
            table_label: "TABLE:",
            terminal_label: "Terminal:",
            guests_label: "Guests:",
            opened_label: "Opened:",
            closed_label: "Closed:  ",
            void_reason_label: "VOIDED:",
            col_qty: "QTY",
            col_desc: "DESCRIPTION",
            col_price: "PRICE",
            col_amount: "AMOUNT",
            discount_prefix: "> DISC",
            before_price_label: " WAS ",
            subtotal_label: "SUBTOTAL",
            savings: "SAVINGS",
            total_units_label: "Total Items:",
            units_word: "pcs",
            col_tax_rate: "TAX",
            col_tax_base: "BASE",
            col_tax_amount: "TAX AMT",
            total_label: "TOTAL",
            tax_included: "TAX INCLUDED",
            farewell: "*** THANK YOU ***",
            credit_note_title: "CREDIT NOTE",
            credit_note_num_label: "No:",
            original_receipt_label: "Original receipt:",
            col_article: "ITEM",
            col_cant: "QTY",
            iva_label: "Tax:",
            credit_subtotal_label: "Subtotal:",
            refund_method_label: "Method:",
            refund_reason_label: "Reason:",
            authorizer_label: "Authorized:",
            cashier_label: "Cashier:",
            refund_cash: "CASH",
            refund_card: "CARD",
            takeaway_title: "Takeaway",
            takeaway_tag: "[TO-GO]",
            spec_label: "SPEC:",
            reprint_indicator: "REPRINT",
        },
        // es-ES default (Verifactu compliance language)
        _ => ReceiptText {
            decimal_separator: ",",
            voided: "*** ANULADO ***",
            bill: "*** CUENTA ***",
            reprint: "*** REIMPRESION ***",
            receipt_title: "FACTURA SIMPLIFICADA",
            tax_id_label: "CIF:",
            phone_label: "Tel:",
            email_label: "Email:",
            receipt_num_label: "Num:",
            queue_label: "PEDIDO: #",
            table_label: "MESA:",
            terminal_label: "Terminal:",
            guests_label: "Pers:",
            opened_label: "Apertura:",
            closed_label: "Cierre:  ",
            void_reason_label: "ANULADO:",
            col_qty: "UDS",
            col_desc: "DESCRIPCION",
            col_price: "PVP",
            col_amount: "IMPORTE",
            discount_prefix: "> DESC",
            before_price_label: " ANTES ",
            subtotal_label: "SUBTOTAL",
            savings: "AHORRO",
            total_units_label: "Total Uds:",
            units_word: "uds",
            col_tax_rate: "IVA",
            col_tax_base: "BASE IMP",
            col_tax_amount: "CUOTA",
            total_label: "TOTAL",
            tax_included: "IVA INCLUIDO",
            farewell: "*** GRACIAS POR SU VISITA ***",
            credit_note_title: "NOTA DE CREDITO",
            credit_note_num_label: "No:",
            original_receipt_label: "Factura original:",
            col_article: "ARTICULO",
            col_cant: "CANT.",
            iva_label: "IVA:",
            credit_subtotal_label: "Subtotal:",
            refund_method_label: "Metodo:",
            refund_reason_label: "Motivo:",
            authorizer_label: "Autorizado:",
            cashier_label: "Cajero:",
            refund_cash: "EFECTIVO",
            refund_card: "TARJETA",
            takeaway_title: "Para llevar",
            takeaway_tag: "[LLEVAR]",
            spec_label: "SPEC:",
            reprint_indicator: "REIMPRESION",
        },
    }
}
