DROP TABLE IF EXISTS cloud_commands;
DROP TABLE IF EXISTS cloud_store_info;
DROP TABLE IF EXISTS cloud_daily_reports;
DROP TABLE IF EXISTS cloud_active_orders;
DROP TABLE IF EXISTS cloud_archived_orders;
DROP TABLE IF EXISTS cloud_categories;
DROP TABLE IF EXISTS cloud_products;
DROP TABLE IF EXISTS cloud_sync_cursors;
DROP TABLE IF EXISTS cloud_edge_servers;
