//! Build script to generate TypeScript error codes

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/error/codes.rs");

    // Only generate when env var is set
    if env::var("GENERATE_TS").is_err() {
        return;
    }

    generate_typescript_error_codes();
}

fn generate_typescript_error_codes() {
    let ts_content = r#"// Auto-generated by shared/build.rs - DO NOT EDIT

export const ErrorCode = {
  // 0xxx: General
  Success: 0,
  Unknown: 1,
  ValidationFailed: 2,
  NotFound: 3,
  AlreadyExists: 4,
  InvalidRequest: 5,
  InvalidFormat: 6,
  RequiredField: 7,
  ValueOutOfRange: 8,

  // 1xxx: Auth
  NotAuthenticated: 1001,
  InvalidCredentials: 1002,
  TokenExpired: 1003,
  TokenInvalid: 1004,
  SessionExpired: 1005,
  AccountLocked: 1006,
  AccountDisabled: 1007,

  // 2xxx: Permission
  PermissionDenied: 2001,
  RoleRequired: 2002,
  AdminRequired: 2003,
  CannotModifyAdmin: 2004,
  CannotDeleteAdmin: 2005,

  // 3xxx: Tenant
  TenantNotSelected: 3001,
  TenantNotFound: 3002,
  ActivationFailed: 3003,
  CertificateInvalid: 3004,
  LicenseExpired: 3005,

  // 4xxx: Order
  OrderNotFound: 4001,
  OrderAlreadyPaid: 4002,
  OrderAlreadyCompleted: 4003,
  OrderAlreadyVoided: 4004,
  OrderHasPayments: 4005,
  OrderItemNotFound: 4006,
  OrderEmpty: 4007,

  // 5xxx: Payment
  PaymentFailed: 5001,
  PaymentInsufficientAmount: 5002,
  PaymentInvalidMethod: 5003,
  PaymentAlreadyRefunded: 5004,
  PaymentRefundExceedsAmount: 5005,

  // 6xxx: Product
  ProductNotFound: 6001,
  ProductInvalidPrice: 6002,
  ProductOutOfStock: 6003,
  CategoryNotFound: 6101,
  CategoryHasProducts: 6102,
  CategoryNameExists: 6103,
  SpecNotFound: 6201,
  AttributeNotFound: 6301,
  AttributeBindFailed: 6302,

  // 7xxx: Table
  TableNotFound: 7001,
  TableOccupied: 7002,
  TableAlreadyEmpty: 7003,
  ZoneNotFound: 7101,
  ZoneHasTables: 7102,
  ZoneNameExists: 7103,

  // 8xxx: Employee
  EmployeeNotFound: 8001,
  EmployeeUsernameExists: 8002,
  EmployeeCannotDeleteSelf: 8003,
  RoleNotFound: 8101,
  RoleNameExists: 8102,
  RoleInUse: 8103,

  // 9xxx: System
  InternalError: 9001,
  DatabaseError: 9002,
  NetworkError: 9003,
  TimeoutError: 9004,
  ConfigError: 9005,
  BridgeNotInitialized: 9101,
  BridgeNotConnected: 9102,
  BridgeConnectionFailed: 9103,
  PrinterNotAvailable: 9201,
  PrintFailed: 9202,
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export function isSuccess(code: number | null | undefined): boolean {
  return code === 0 || code === null || code === undefined;
}

export function isError(code: number | null | undefined): boolean {
  return code !== null && code !== undefined && code !== 0;
}

export interface ApiResponse<T = unknown> {
  code: number | null;
  message: string;
  data: T | null;
  details?: Record<string, unknown> | null;
}
"#;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_path = Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("red_coral/src/generated/error-codes.ts");

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).ok();
    }

    fs::write(&out_path, ts_content).ok();
}
