//! Build script to generate TypeScript error codes

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/error/codes.rs");
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs/heads/");

    // Embed git hash at compile time
    // Prefer GIT_HASH env var (set by Docker build-arg), fallback to git command
    let git_hash = env::var("GIT_HASH")
        .ok()
        .filter(|s| !s.is_empty() && s != "dev")
        .unwrap_or_else(|| {
            std::process::Command::new("git")
                .args(["rev-parse", "--short", "HEAD"])
                .output()
                .ok()
                .and_then(|o| String::from_utf8(o.stdout).ok())
                .map(|s| s.trim().to_string())
                .unwrap_or_else(|| "unknown".to_string())
        });
    println!("cargo:rustc-env=GIT_HASH={git_hash}");

    // Only generate when env var is set
    if env::var("GENERATE_TS").is_err() {
        return;
    }

    generate_typescript_error_codes();
}

fn generate_typescript_error_codes() {
    let ts_content = r#"// Auto-generated by shared/build.rs - DO NOT EDIT

export const ErrorCode = {
  // 0xxx: General
  Success: 0,
  Unknown: 1,
  ValidationFailed: 2,
  NotFound: 3,
  AlreadyExists: 4,
  InvalidRequest: 5,
  InvalidFormat: 6,
  RequiredField: 7,

  // 1xxx: Auth
  NotAuthenticated: 1001,
  InvalidCredentials: 1002,
  TokenExpired: 1003,
  SessionExpired: 1005,
  AccountDisabled: 1007,

  // 2xxx: Permission
  PermissionDenied: 2001,
  AdminRequired: 2003,

  // 3xxx: Tenant
  TenantNotSelected: 3001,
  TenantNotFound: 3002,
  ActivationFailed: 3003,
  CertificateInvalid: 3004,
  LicenseExpired: 3005,
  SubscriptionBlocked: 3006,
  StoreLimitReached: 3007,
  TenantCredentialsInvalid: 3009,
  TenantNoSubscription: 3011,
  AuthServerError: 3012,
  VerificationCodeExpired: 3013,
  VerificationCodeInvalid: 3014,
  TooManyAttempts: 3015,
  PaymentSetupFailed: 3017,
  PasswordTooShort: 3018,
  P12Required: 3019,
  ResourceLimitExceeded: 3022,
  P12InvalidFormat: 3023,
  P12WrongPassword: 3024,
  P12MissingPrivateKey: 3025,
  P12MissingCertificate: 3026,
  P12ChainVerifyFailed: 3027,
  P12UntrustedCa: 3028,
  P12NifMismatch: 3029,
  P12CertExpired: 3030,
  P12CertNotYetValid: 3031,

  // 4xxx: Order
  OrderNotFound: 4001,
  OrderAlreadyCompleted: 4003,
  OrderAlreadyVoided: 4004,
  OrderItemNotFound: 4006,
  OrderNotCompleted: 4008,
  OrderHasCreditNotes: 4009,
  CreditNoteOverRefund: 4010,
  CreditNoteItemOverRefund: 4011,
  OrderVoidedNoCreditNote: 4012,
  OrderAlreadyUpgraded: 4013,
  ImportInvalidFormat: 4015,
  ExportFailed: 4016,

  // 6xxx: Product
  ProductNotFound: 6001,
  ProductInvalidPrice: 6002,
  CategoryNotFound: 6101,
  CategoryHasProducts: 6102,
  SpecRootRequired: 6205,
  ProductExternalIdExists: 6202,
  ProductExternalIdRequired: 6203,
  ProductCategoryInvalid: 6204,
  AttributeNotFound: 6301,
  AttributeBindFailed: 6302,
  AttributeInUse: 6303,
  AttributeDuplicateBinding: 6304,
  TagNotFound: 6401,
  TagInUse: 6402,

  PrintDestinationNotFound: 6511,
  PrintDestinationInUse: 6512,
  MarketingGroupNotFound: 6601,
  LabelTemplateNotFound: 6701,
  PriceRuleNotFound: 6801,
  PriceRuleValueOutOfRange: 6802,

  // 7xxx: Table
  TableNotFound: 7001,
  TableOccupied: 7002,
  ZoneNotFound: 7101,
  ZoneHasTables: 7102,
  TableHasOrders: 7104,
  ShiftNotFound: 7201,
  DailyReportNotFound: 7301,

  // 8xxx: Employee
  EmployeeNotFound: 8001,
  EmployeeIsSystem: 8004,
  MemberNotFound: 8005,
  RoleNotFound: 8101,
  RoleIsSystem: 8104,

  // 9xxx: System
  InternalError: 9001,
  DatabaseError: 9002,
  NetworkError: 9003,
  TimeoutError: 9004,
  ConfigError: 9005,
  PasswordHashingFailed: 9006,
  BridgeNotInitialized: 9101,
  BridgeNotConnected: 9102,
  BridgeConnectionFailed: 9103,
  PrinterNotAvailable: 9201,
  PrintFailed: 9202,
  PrintNoPrintersConfigured: 9203,
  PrintAllPrintersOffline: 9204,
  ClientDisconnected: 9301,
  ArchiveHashChainError: 9302,
  InvoiceNumberError: 9303,
  InvoiceConversionError: 9304,

  // 94xx: Storage
  StorageFull: 9401,
  OutOfMemory: 9402,
  StorageCorrupted: 9403,
  SystemBusy: 9404,
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export function isSuccess(code: number | null | undefined): boolean {
  return code === 0 || code === null || code === undefined;
}

export function isError(code: number | null | undefined): boolean {
  return code !== null && code !== undefined && code !== 0;
}

export interface ApiResponse<T = unknown> {
  code: number | null;
  message: string;
  data: T | null;
  details?: Record<string, unknown> | null;
}
"#;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_path = Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("red_coral/src/generated/error-codes.ts");

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).ok();
    }

    fs::write(&out_path, ts_content).ok();
}
